import type { TenantConfig } from './types';
export const ecoclub: TenantConfig = {
  id: 'ecoclub',
  displayName: 'EcoClub',
  stackPrefix: 'EcoClub',
  leagueName: 'SmartClub Ahorro',
  groupName: 'Farmaenlace',
  tagline: 'Tus compras de siempre. Más motivos para volver.',
  rewardCodePrefix: 'ECO',
  theme: {
    surface: '#ffffff',
    'surface-muted': '#f1f2f4',
    ink: '#191918',
    'ink-muted': '#5f666d',
    line: '#899199',
    'line-subtle': '#b3b3b1',
    danger: '#ea0029',
    success: '#1d8649',
    'tier-bronze': '#c27c3a',
    'tier-silver': '#b3b3b1',
    'tier-gold': '#f2b705',
    'brand-on-strong': '#ffffff',
    'brand-secondary': '#002d74',
    'brand-primary': '#80bc00',
    'brand-primary-strong': '#1d8649',
    'brand-accent': '#6abf4b',
    'brand-soft': '#d9e8ab',
    'brand-gradient': 'linear-gradient(90deg,#1d8649 34%,#6abf4b 100%)',
  },
  businesses: [
    {
      businessId: 'farmacias-economicas',
      name: 'Farmacias Económicas',
      brand: 'Económicas',
      category: 'PHARMACY',
      description: 'Suma tus compras en Farmacias Económicas',
      active: true,
    },
  ],
  streak: {
    streakId: 'liga-ahorro',
    name: 'SmartClub Ahorro',
    description: 'Cada compra suma. Mantén tu nivel y desbloquea beneficios.',
    period: 'CALENDAR_MONTH',
    timeZone: 'America/Guayaquil',
    businessIds: ['farmacias-economicas'],
    active: true,
    version: 1,
    tiers: [
      {
        tierId: 'BRONZE',
        name: 'Bronce',
        minMonthlyCents: 1000,
        receiptTeaser: '5% de cashback en tu próxima compra',
        rewards: [
          {
            rewardId: 'bronce-cashback',
            requiredConsecutiveMonths: 1,
            selection: 'ALL',
            validForMonths: 1,
            benefits: [
              {
                benefitId: 'cashback',
                type: 'PERCENT_DISCOUNT',
                title: '5% de cashback en tu próxima compra',
                description: 'Un descuento de 5% sobre el valor de tu próxima compra. Un solo uso.',
                percent: 5,
              },
            ],
          },
        ],
      },
      {
        tierId: 'SILVER',
        name: 'Plata',
        minMonthlyCents: 1500,
        receiptTeaser: 'un cupón de $2 o acceso anticipado a Días Especiales',
        rewards: [
          {
            rewardId: 'plata-eleccion',
            requiredConsecutiveMonths: 3,
            selection: 'ONE_OF',
            validForMonths: 2,
            benefits: [
              {
                benefitId: 'acceso',
                type: 'SPECIAL_DAYS_EARLY_ACCESS',
                title: 'Acceso anticipado a Días Especiales',
                description: 'Acceso anticipado a Días Especiales',
              },
              {
                benefitId: 'cupon-2',
                type: 'FIXED_DISCOUNT',
                title: 'Cupón de $2',
                description: 'Cupón de $2',
                amountCents: 200,
              },
            ],
          },
        ],
      },
      {
        tierId: 'GOLD',
        name: 'Oro',
        minMonthlyCents: 2500,
        receiptTeaser: 'un cupón de envío a domicilio gratis',
        rewards: [
          {
            rewardId: 'oro-beneficios',
            requiredConsecutiveMonths: 3,
            selection: 'ALL',
            validForMonths: 2,
            benefits: [
              {
                benefitId: 'dias-especiales',
                type: 'SPECIAL_DAYS_DISCOUNT',
                title: 'Hasta 25% en Días Especiales',
                description: 'Hasta 25% en Días Especiales',
                percent: 25,
              },
              {
                benefitId: 'envio',
                type: 'FREE_DELIVERY',
                title: 'Envío a domicilio gratis',
                description: 'Envío a domicilio gratis',
                monthlyInstallments: 3,
              },
            ],
          },
        ],
      },
    ],
  },
};
