import type { TenantConfig } from './types';
export const farmaclub: TenantConfig = {
  id: 'farmaclub',
  displayName: 'FarmaClub',
  stackPrefix: 'FarmaClub',
  leagueName: 'SmartClub Wellness',
  groupName: 'Farmaenlace',
  tagline: 'Tu bienestar conecta. Tus compras te recompensan.',
  rewardCodePrefix: 'FRM',
  theme: {
    surface: '#ffffff',
    'surface-muted': '#f1f2f4',
    ink: '#191918',
    'ink-muted': '#5f666d',
    line: '#899199',
    'line-subtle': '#b3b3b1',
    danger: '#ea0029',
    success: '#1d8649',
    'tier-bronze': '#c27c3a',
    'tier-silver': '#b3b3b1',
    'tier-gold': '#f2b705',
    'brand-on-strong': '#ffffff',
    'brand-secondary': '#002d74',
    'brand-primary': '#0570b7',
    'brand-primary-strong': '#002d74',
    'brand-accent': '#80bc00',
    'brand-soft': '#e1eef6',
    'brand-gradient': 'linear-gradient(-22deg,#002d74 0,#006098 83%)',
  },
  businesses: [
    {
      businessId: 'medicity',
      name: 'Medicity',
      brand: 'Medicity',
      category: 'PHARMACY',
      description: 'Suma tus compras en Medicity',
      active: true,
    },
    {
      businessId: 'wellderma',
      name: 'Wellderma',
      brand: 'Wellderma',
      category: 'DERMOCOSMETICS',
      description: 'Suma tus compras en Wellderma',
      active: true,
    },
    {
      businessId: 'mascotas',
      name: 'Mascotas',
      brand: 'Mascotas',
      category: 'PETS',
      description: 'Suma tus compras en Mascotas',
      active: true,
    },
    {
      businessId: 'ambiente',
      name: 'Ambiente',
      brand: 'Ambiente',
      category: 'HOME',
      description: 'Suma tus compras en Ambiente',
      active: true,
    },
  ],
  streak: {
    streakId: 'liga-wellness',
    name: 'SmartClub Wellness',
    description: 'Bienestar, belleza, hogar y mascotas: todas tus marcas suman.',
    period: 'CALENDAR_MONTH',
    timeZone: 'America/Guayaquil',
    businessIds: ['medicity', 'wellderma', 'mascotas', 'ambiente'],
    active: true,
    version: 1,
    tiers: [
      {
        tierId: 'BRONZE',
        name: 'Bronce',
        minMonthlyCents: 3000,
        receiptTeaser: '5% de cashback y un café de cortesía',
        rewards: [
          {
            rewardId: 'bronce-bienestar',
            requiredConsecutiveMonths: 1,
            selection: 'ALL',
            validForMonths: 1,
            benefits: [
              {
                benefitId: 'cashback',
                type: 'PERCENT_DISCOUNT',
                title: '5% de cashback en tu próxima compra',
                description: 'Un descuento de 5% sobre el valor de tu próxima compra. Un solo uso.',
                percent: 5,
              },
              {
                benefitId: 'cafe',
                type: 'IN_STORE_PERK',
                title: 'Café de cortesía en tu visita',
                description: 'Café de cortesía en tu visita',
              },
            ],
          },
        ],
      },
      {
        tierId: 'SILVER',
        name: 'Plata',
        minMonthlyCents: 6000,
        receiptTeaser: 'consulta dermatológica exprés, muestras premium y Fast Track',
        rewards: [
          {
            rewardId: 'plata-bienestar',
            requiredConsecutiveMonths: 3,
            selection: 'ALL',
            validForMonths: 2,
            benefits: [
              {
                benefitId: 'consulta',
                type: 'IN_STORE_PERK',
                title: 'Consulta dermatológica exprés',
                description: 'Consulta dermatológica exprés',
              },
              {
                benefitId: 'muestras',
                type: 'IN_STORE_PERK',
                title: 'Muestras médicas premium',
                description: 'Muestras médicas premium de laboratorios aliados',
              },
              {
                benefitId: 'fast-track',
                type: 'IN_STORE_PERK',
                title: 'Fila Fast Track en Medicity',
                description: 'Fila Fast Track en Medicity',
                businessIds: ['medicity'],
              },
            ],
          },
        ],
      },
      {
        tierId: 'GOLD',
        name: 'Oro',
        minMonthlyCents: 12000,
        receiptTeaser: 'una experiencia exclusiva para ti',
        rewards: [
          {
            rewardId: 'oro-experiencia',
            requiredConsecutiveMonths: 3,
            selection: 'ONE_OF',
            validForMonths: 2,
            benefits: [
              {
                benefitId: 'diseno',
                type: 'PARTNER_EXPERIENCE',
                title: 'Asesoría de diseño de interiores',
                description: 'Asesoría de diseño de interiores',
                businessIds: ['ambiente'],
              },
              {
                benefitId: 'grooming',
                type: 'PARTNER_EXPERIENCE',
                title: 'Sesión de grooming para tu mascota',
                description: 'Sesión de grooming para tu mascota',
                businessIds: ['mascotas'],
              },
              {
                benefitId: 'byd',
                type: 'PARTNER_EXPERIENCE',
                title: 'Prueba de manejo BYD',
                description: 'Fin de semana de prueba de manejo BYD',
                partnerName: 'BYD',
              },
            ],
          },
        ],
      },
    ],
  },
};
